# Generated by Django 5.2.1 on 2026-02-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם הלקוחה')),
                ('phone', models.CharField(max_length=15, verbose_name='טלפון')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל')),
                ('notes', models.TextField(blank=True, verbose_name='העדפות / הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצרה בתאריך')),
            ],
            options={
                'verbose_name': 'לקוחה',
                'verbose_name_plural': 'לקוחות',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('face', 'טיפול פנים'), ('brows', 'עיצוב גבות'), ('gel', "לק ג'ל")], max_length=20, verbose_name='סוג טיפול')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='מחיר לטיפול')),
                ('start_time', models.DateTimeField(verbose_name='זמן התחלה')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='משך (בדקות)')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('is_completed', models.BooleanField(default=False, verbose_name='בוצע?')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.client', verbose_name='לקוחה')),
            ],
            options={
                'verbose_name': 'תור',
                'verbose_name_plural': 'תורים',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('income', 'הכנסה'), ('expense', 'הוצאה')], max_length=10, verbose_name='סוג תנועה')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='סכום')),
                ('category', models.CharField(max_length=100, verbose_name='קטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='appointments.appointment', verbose_name='תור קשור')),
            ],
            options={
                'verbose_name': 'רישום כספי',
                'verbose_name_plural': 'רישומים כספיים',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
