# Generated by Django 5.2.1 on 2026-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='כותרת אירוע')),
                ('start_time', models.DateTimeField(verbose_name='זמן התחלה')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='זמן סיום')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
            ],
            options={
                'verbose_name': 'אירוע אישי',
                'verbose_name_plural': 'אירועים אישיים',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='גיל'),
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='תאריך לידה'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='שם מלא'),
        ),
    ]
