# Generated by Django 5.2.1 on 2026-02-27 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_personalevent_client_age_client_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='שם מלא')),
                ('phone_number', models.CharField(max_length=15, verbose_name='טלפון')),
                ('age', models.PositiveIntegerField(verbose_name='גיל')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='אימייל - אופציונלי')),
                ('roaccutane', models.BooleanField(default=False, verbose_name='שימוש בראוקוטן בשנה האחרונה')),
                ('active_peeling', models.BooleanField(default=False, verbose_name='שימוש בתכשירים מקלפים פעילים')),
                ('prescription_creams', models.BooleanField(default=False, verbose_name='תכשירים במרשם רופא')),
                ('past_acne', models.BooleanField(default=False, verbose_name='אקנה בעבר')),
                ('skin_diseases', models.BooleanField(default=False, verbose_name='מחלות עור')),
                ('regular_meds', models.BooleanField(default=False, verbose_name='תרופות קבועות')),
                ('hormonal_contraceptives', models.BooleanField(default=False, verbose_name='גלולות/התקן הורמונלי')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='הריון/הנקה')),
                ('cosmetic_allergies', models.BooleanField(default=False, verbose_name='אלרגיה לתכשירים')),
                ('numbing_sensitivity', models.BooleanField(default=False, verbose_name='רגישות לאלחוש/עזרקאין')),
                ('metal_sensitivity', models.BooleanField(default=False, verbose_name='רגישות למתכות - תכשיטים')),
                ('general_allergies', models.BooleanField(default=False, verbose_name='אלרגיות למזון/חומרים אחרים')),
                ('medical_notes', models.TextField(blank=True, verbose_name='פירוט נוסף')),
                ('treatment_reactions', models.TextField(blank=True, verbose_name='תגובות חריפות לטיפולים בעבר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך מילוי')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP לצרכי תיעוד')),
            ],
            options={
                'verbose_name': 'הצהרת בריאות',
                'verbose_name_plural': 'הצהרות בריאות',
                'ordering': ['-created_at'],
            },
        ),
    ]
