# Generated by Django 5.2.1 on 2026-02-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_health_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdeclaration',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_declaration', to='appointments.client', verbose_name='לקוחה'),
        ),
        migrations.AddField(
            model_name='healthdeclaration',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='הוגשה'),
        ),
        migrations.AlterField(
            model_name='healthdeclaration',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='גיל'),
        ),
        migrations.AlterField(
            model_name='healthdeclaration',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='שם מלא'),
        ),
        migrations.AlterField(
            model_name='healthdeclaration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='טלפון'),
        ),
    ]
