# Generated by Django 5.2.1 on 2026-02-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_health_client_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financerecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='appointments.appointment', verbose_name='תור קשור'),
        ),
    ]
